version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
#                --region us-east-1
  update_inventory_list:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - run:
          command: |
            # export AWS_ACCESS_KEY_ID=${aws_secret_id}
            # export AWS_SECRET_ACCESS_KEY=${aws_access_key}
            # export AWS_DEFAULT_REGION=us-east-1
            touch ~/inventory
            echo [all] > ~/inventory
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Project,Values=udacity" \
              --output text >> ~/inventory
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory
  configure_infrastructure:
    docker:
      - image: python:3.11-rc-alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e3:d2:59:7a:82:97:7d:e5:c4:b4:86:31:a1:83:63:fc"
      - attach_workspace:
          at: ~/
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook to configure server
          command: |
            ansible-playbook -i ~/inventory main-remote.yml

workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
      - update_inventory_list:
          requires:
            - create_infrastructure
      - configure_infrastructure:
          requires:
            - update_inventory_list

      