---
- name: "update apt packages."
#  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
#  become: yes
  apt:
    upgrade: yes

- name: install dependancies
  apt:
    name:
      - nodejs
      - npm
    state: latest

- name: install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create web directory
  file:
    path: ~/web
    state: directory

- name: copy index.js to web dir
  copy:
    src: index.js
    dest: ~/web/index.js   

- name: start web server
  command: pm2 start ~/web/index.js -f
